In [2]:
from PIL import Image
from torchvision import transforms
import torch
import numpy as np

label_path = "/home/zekun/drivable/data/bdd100k/labels/10k/ins_seg/bitmasks/val/82ad9d1c-1a5212c8.png"
# label_path = "/home/zekun/drivable/data/bdd100k/labels/100k/drivable/masks/val/b1c66a42-6f7d68ca.png"

label = Image.open(label_path)
print(np.array(label))
print(np.unique(np.array(label)), len(np.unique(np.array(label))))
print()

def replace_255_with_20(label):
    # label = np.array(label)
    label[label==255] = 20
    # return Image.fromarray(label)
    return label

transform = transforms.Compose(
    [
        
        transforms.Resize((512,1024), transforms.InterpolationMode.NEAREST),
        transforms.ToTensor(),
        transforms.Lambda(lambda x: x.squeeze())
        # transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ]
)

label = transform(label)
print(np.unique(np.array(label)), len(np.unique(np.array(label))))
print()
# Convert label to tensor and convert from RGB to single channel (grayscale)
label = (label*255).to(torch.int64)
print(np.unique(np.array(label)), len(np.unique(np.array(label))))
print()

label = torch.nn.functional.one_hot(label, num_classes=21).permute(2, 0, 1).float()
print(label.shape)
# print(label[label2=])

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 ...

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[0 1 2 3 4 5] 6

[0.         0.00392157 0.00784314 0.01176471 0.01568628 0.01960784] 6

[0 1 2 3 4 5] 6



RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 4 is not equal to len(dims) = 3

In [41]:
arr1 = [1,2,3]
arr2 = [1,3,2]

print(np.logical_and(arr1, arr2))

[ True  True  True]


In [4]:
from lib.utils.dbhandler import JsonDBHandler

handler = JsonDBHandler.create_db("/home/zekun/drivable/outputs/obj_det/db")


In [15]:
from torchvision.io.image import read_image
from torchvision.models.detection import fasterrcnn_resnet50_fpn_v2, FasterRCNN_ResNet50_FPN_V2_Weights
from torchvision.utils import draw_bounding_boxes
from torchvision.transforms.functional import to_pil_image

img = read_image("../data/bdd100k/images/10k/val/7d06fefd-f7be05a6.jpg")

# Step 1: Initialize model with the best available weights
weights = FasterRCNN_ResNet50_FPN_V2_Weights.DEFAULT
model = fasterrcnn_resnet50_fpn_v2(weights=weights, box_score_thresh=0.9)
model.eval()

# Step 2: Initialize the inference transforms
preprocess = weights.transforms()

# Step 3: Apply inference preprocessing transforms
batch = [preprocess(img)]

# Step 4: Use the model and visualize the prediction
prediction = model(batch)[0]
labels = [weights.meta["categories"][i] for i in prediction["labels"]]
box = draw_bounding_boxes(img, boxes=prediction["boxes"],
                          labels=labels,
                          colors="red",
                          width=4, font_size=30)
im = to_pil_image(box.detach())
im.save("ttt.jpg")

In [25]:
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', autoshape=False, pretrained=True)

# Images
imgs = ['https://ultralytics.com/images/zidane.jpg']  # batch of images

print(type(model))
# Inference
results = model(imgs)
print(type(results))
# Results
results.print()
# results.save()  # or .show()

results.xyxy[0]  # img1 predictions (tensor)
results.pandas().xyxy[0]  # img1 predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 1  433.50  433.50   517.5  714.5    0.687988     27     tie
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

Using cache found in /home/zekun/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2023-12-11 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)



<class 'models.common.DetectMultiBackend'>


AttributeError: 'list' object has no attribute 'shape'

In [4]:
from ultralytics.utils import yaml_load
from ultralytics.cfg import get_cfg
from ultralytics.data.utils import check_det_dataset

cfg = get_cfg(overrides={"data": "/home/zekun/drivable/test/yolo/bdd100k_yolo.yaml"})
data = check_det_dataset(cfg.data)
print(data)
# print(yaml_load("/home/zekun/drivable/test/yolo/bdd100k_yolo.yaml"))

{'path': PosixPath('/home/zekun/drivable/tmp/dataset'), 'train': ['/home/zekun/drivable/tmp/dataset/images/train', '/home/zekun/drivable/tmp/dataset/images/val'], 'val': '/home/zekun/drivable/tmp/dataset/images/val', 'names': {0: 'pedestrian', 1: 'rider', 2: 'car', 3: 'truck', 4: 'bus', 5: 'train', 6: 'motorcycle', 7: 'bicycle', 8: 'traffic light', 9: 'traffic sign'}, 'yaml_file': '/home/zekun/drivable/test/yolo/bdd100k_yolo.yaml', 'nc': 10}
